ren App.php xApp.php
ren Common.php xCommon.php
ren Constant.php xConstant.php
ren Cookie.php xCookie.php
ren CookieEntity.php xCookieEntity.php
ren Entity.php xEntity.php
ren Environment.php xEnvironment.php
ren Id.php xId.php
ren Info.php xInfo.php
ren Ip.php xIp.php
ren IpCheck.php xIpCheck.php
ren Item.php xItem.php
ren ItemGetApi.php xItemGetApi.php
ren ItemSetApi.php xItemSetApi.php
ren Login.php xLogin.php
ren LoginApi.php xLoginApi.php
ren LoginEntity.php xLoginEntity.php
ren phpinfo.php xphpinfo.php
ren User.php xUser.php
ren UserActivateApi.php xUserActivateApi.php
ren UserCreateApi.php xUserCreateApi.php
ren UserEntity.php xUserEntity.php
ren UserMaxId.php xUserMaxId.php
